using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Events;
using Unity.Netcode;

public class LobbyManager : NetworkBehaviour
{
    public UnityEvent loadMap;

    public NetworkStore netStore;

    // Start is called before the first frame update
    void Start()
    {
        NetworkManager.Singleton.OnClientConnectedCallback += (id) =>
        {
            if (IsHost)
            {
                ++netStore.playersInLobby.Value;

                Logger.Instance.LogInfo($"Player {id} just joined the lobby");
                Logger.Instance.LogInfo($"Current number of players in lobby: {netStore.playersInLobby.Value}");

                
            }
            else
            {
                Logger.Instance.LogInfo($"Player {id} just joined the lobby");
                Logger.Instance.LogInfo($"Current number of players in lobby: {netStore.playersInLobby.Value}");

                // Load map generated by Host
                loadMap.Invoke();
                Logger.Instance.LogInfo("Loaded map");
            }
        };

        NetworkManager.Singleton.OnClientDisconnectCallback += (id) =>
        {
            if (IsHost)
            {
                --netStore.playersInLobby.Value;
                Logger.Instance.LogInfo($"Player {id} just left the lobby");
                Logger.Instance.LogInfo($"Current number of players in lobby: {netStore.playersInLobby.Value}");       
            }
            else
            {
                Logger.Instance.LogInfo($"Player {id} just joined the lobby");
                Logger.Instance.LogInfo($"Current number of players in lobby: {netStore.playersInLobby.Value}");
                
            }
        };
    }

    // Update is called once per frame
    void Update()
    {
        
    }


}
